### ISSUE TITLE
silverback-drupal app is not compatible with composer 2

### ISSUE THREAD

**Issue by JohnAlbin** [amazeeio-solutions/silverback-mono#481]
When using composer 2, the `composer install` command fails with:

```
wikimedia/composer-merge-plugin dev-master requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```

Upstream bug report: https://github.com/wikimedia/composer-merge-plugin/issues/184

Since we are doing `composer install` as a postinstall task of the Drupal app and `yarn install` causes an install of both Drupal and Gatsby apps, this means if you are trying to use the Gatsby starter app, the `yarn install` command fails because the app you don't want to use (Drupal) can't be installed properly.

2 possible fixes:

* Remove the `"scripts": { "postinstall": "composer install" },` lines from `apps/silverback-drupal/package.json`.
* Remove the `"wikimedia/composer-merge-plugin": "^1.4"` line from `packages/composer/amazeelabs/silverback-cli/composer.json`. We can add it back later when it is compatible with Composer 2.

…or we can do both.

**Comment by JohnAlbin** [comment]
I'm leaning towards doing both of these things.

1. If you are installing the Drupal app, most would already know you need to run `composer install` and we can add it to that app's README for those that don't know to run it.
2. If you are installing the Gatsby app, you don't want a composer command taking up install time and disk space.
3. If we just did the first option (remove postintall), that still doesn't fix the composer 2 problem.

**Comment by JohnAlbin** [comment]
We have an additional problem to fixing composer 2 compatibility. The `apps/silverback-drupal/composer.lock` file has locked `amazeelabs/silverback-cli` to an older version that doesn't support Composer 2.

The `apps/sliverback-drupal/composer.lock` shows:

```
        {
            "name": "amazeelabs/silverback-cli",
            "version": "dev-drupal-cypress",
            "dist": {
                "type": "path",
                "url": "../../packages/composer/amazeelabs/silverback-cli",
                "reference": "75ee1e347d8abf06b0ae102f28013620509202ce"
            },
            "require": {
                "alchemy/zippy": "dev-master",
                "cweagans/composer-patches": "^1.6.7",
                "drush/drush": "^10.3.4",
                "ext-zip": "*",
                "vlucas/phpdotenv": "^5.1",
                "wikimedia/composer-merge-plugin": "^1.4"
            },
```

But that version of cweagans/composer-patches isn't compatible with Composer 2. Also, `packages/composer/amazeelabs/silverback-cli/composer.json` shows newer dependencies:

```
    "require": {
        "ext-zip": "*",
        "alchemy/zippy": "dev-master",
        "cweagans/composer-patches": "^1.7.0",
        "drush/drush": "^10.3.6",
        "vlucas/phpdotenv": "^5.2",
        "wikimedia/composer-merge-plugin": "^1.4"
    },
```

I think we need to remove the `apps/silverback-drupal/composer.lock` file from the repo.

**Comment by Leksat** [comment]
Why not just wait till https://github.com/wikimedia/composer-merge-plugin/issues/184 is fixed and use Composer 1 for now?

**Comment by JohnAlbin** [comment]
> Why not just wait till wikimedia/composer-merge-plugin#184 is fixed and use Composer 1 for now?

I am, but that doesn't solve the other 2 problems (composer.lock is outdated and gatsby starter users shouldn't be running `composer install`).

**Comment by dan2k3k4** [comment]
In case we need to check any other plugins being used, Drupal has a full documentation page about [preparing your site for Composer 2](https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2)

**Comment by JohnAlbin** [comment]
With the PR at #482, I can run `yarn install; cd apps/silverback-drupal; composer install` without errors using Composer v2. I have not tested with Composer v1.

**Comment by Leksat** [comment]
Fixed in #500 and #502.
